=== SerraMM/LenguaDeMarcasTareas/SimulacroLMPRUEBA2/Ejercicio2/biblioteca4.dtd
<!ELEMENT biblioteca (libro,revista,periodico)>
<!ELEMENT libro (titulo,autor,fechaPublicacion)>
<!ELEMENT revista (titulo,fechaPublicacion)>
<!ELEMENT periodico (titulo,fechaPublicacion)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT fechaPublicacion (#PCDATA)>
<!ATTLIST numeroDePaginas libro CDATA #REQUIRED>

=== SerraMM/LenguaDeMarcasTareas/SimulacroLMPRUEBA2/Ejercicio2/biblioteca4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "./biblioteca4.dtd">
<biblioteca>
    <libro>
        <titulo>Sin permiso</titulo>
        <autor>SP</autor>
        <fechaPublicacion>1936</fechaPublicacion>
    </libro>
    <revista>
        <titulo>MQC</titulo>
        <fechaPublicacion>1976</fechaPublicacion>
    </revista>
    <periodico>
        <titulo>ABC</titulo>
        <fechaPublicacion>1926</fechaPublicacion>
    </periodico>
</biblioteca>
